project_id = "ceasktzguzibehknbgsx"

[functions.generate-email-reply]
verify_jwt = false

[functions.send-email-reply]
verify_jwt = false

[functions.backup-system]
verify_jwt = true

[functions.restore-backup]
verify_jwt = true

[functions.platform-assistant]
verify_jwt = true

[functions.create-teams-bot]
verify_jwt = true

[functions.teams-bot-webhook]
verify_jwt = false

[functions.bot-endpoint-test]
verify_jwt = false

[functions.auto-email-scheduler]
verify_jwt = false

[functions.auto-process-pending-emails]
verify_jwt = false

[functions.create-mailbox]
verify_jwt = true

[functions.manage-mailbox-state]
verify_jwt = true

[functions.process-meeting-transcript]
verify_jwt = true

[functions.mailbox-api]
verify_jwt = false

[functions.mailbox-oauth-callback]
verify_jwt = true

[functions.classify-email]
verify_jwt = false

[functions.email-poller]
verify_jwt = false

[functions.ai-email-classifier]
verify_jwt = false

[functions.ai-condition-evaluator]
verify_jwt = false

[functions.email-workflow-processor]
verify_jwt = false

[functions.process-email-backlog]
verify_jwt = false

[functions.trigger-email-processing]
verify_jwt = false

[functions.threat-intelligence-checker]
verify_jwt = false

[functions.feed-health-monitor]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.clear-email-queue]
verify_jwt = false

[functions.system-health-check]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.reprocess-emails]
verify_jwt = true