project_id = "ceasktzguzibehknbgsx"

[functions.platform-assistant]
verify_jwt = true

[functions.auto-email-scheduler]
verify_jwt = false

[functions.auto-process-pending-emails]
verify_jwt = false

[functions.mailbox-api]
verify_jwt = false

[functions.mailbox-oauth-callback]
verify_jwt = false

[functions.classify-email]
verify_jwt = false

[functions.email-poller]
verify_jwt = false

[functions.ai-email-classifier]
verify_jwt = false

[functions.ai-condition-evaluator]
verify_jwt = false

[functions.email-workflow-processor]
verify_jwt = false

[functions.process-email-backlog]
verify_jwt = false

[functions.trigger-email-processing]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.clear-email-queue]
verify_jwt = false

[functions.system-health-check]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.reprocess-emails]
verify_jwt = true