project_id = "ceasktzguzibehknbgsx"

[functions.auto-email-scheduler]
verify_jwt = false

[functions.mailbox-api]
verify_jwt = false

[functions.mailbox-oauth-callback]
verify_jwt = false

[functions.classify-email]
verify_jwt = false

[functions.email-poller]
verify_jwt = false

[functions.ai-email-classifier]
verify_jwt = false

[functions.ai-condition-evaluator]
verify_jwt = false

[functions.email-workflow-processor]
verify_jwt = false

[functions.create-user]
verify_jwt = true