project_id = "ceasktzguzibehknbgsx"

[functions.mailbox-api]
verify_jwt = false

[functions.mailbox-oauth-callback]
verify_jwt = false

[functions.classify-email]
verify_jwt = false

[functions.email-poller]
verify_jwt = false