version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"  # Changed to 8080 to avoid conflicts with nginx proxy manager
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - web

  # Optional: Add a development service
  app-dev:
    build:
      context: .
      target: build
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev
    networks:
      - web

networks:
  web:
    driver: bridge